// lib/data/local/app_database.dart

import 'dart:io';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:drift/drift.dart';
import 'package:drift/native.dart';

// This line tells Drift to generate code for our database and tables.
// The generated file will be 'app_database.g.dart' in the same directory.
part 'app_database.g.dart';

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'app_database.sqlite'));
    return NativeDatabase(file);
  });
}

/// Represents the 'Books' table in our local SQLite database.
///
/// Each column is defined using Drift's type system.
/// - `id`: An auto-incrementing integer, serving as the primary key.
/// - `title`: A non-nullable text field for the book's title, with a length constraint.
/// - `author`: A non-nullable text field for the book's author, with a length constraint.
/// - `isbn`: A nullable text field for the International Standard Book Number.
///           It's nullable because a book might be added manually without an ISBN.
@DataClassName('BookEntry') // Custom class name for the generated data class
class Books extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get title => text().withLength(min: 1, max: 255)();
  TextColumn get author => text().withLength(min: 1, max: 255)();
  TextColumn get isbn => text().nullable()();
}

/// The main database class for the Ex Libris app.
///
/// This class extends _$AppDatabase (which will be generated by Drift).
/// It links all the tables we define (currently just 'Books').
@DriftDatabase(tables: [Books])
class AppDatabase extends _$AppDatabase {
  // The constructor now initializes with the SQLite connection.
  AppDatabase() : super(_openConnection());

  /// Defines the current schema version.
  /// This is important for database migrations when the schema changes.
  /// For now, we start at version 1.
  @override
  int get schemaVersion => 1;

  // --- DAO (Data Access Object) Methods for Books ---

  /// Retrieves all book entries from the database.
  Future<List<BookEntry>> getAllBooks() => select(books).get();

  /// Inserts a new book into the database.
  /// Returns the ID of the newly inserted row.
  Future<int> insertBook(BooksCompanion entry) => into(books).insert(entry);

  /// Updates an existing book entry in the database.
  /// Returns `true` if a row was updated, `false` otherwise.
  Future<bool> updateBook(BookEntry entry) => update(books).replace(entry);

  /// Deletes a specific book entry from the database by its ID.
  /// Returns the number of rows affected (should be 1 if found).
  Future<int> deleteBook(int id) => (delete(books)..where((t) => t.id.equals(id))).go();
}
